version: '3'
services:
  cache:
    image: redis
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - ./docker/data/redis:/data
  database:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./docker/env/docker.env
    volumes:
      - ./docker/data/pg:/var/lib/postgresql/data


    
    